
#spring:
#  datasource:
#    username: user2
#    password: 2590868
#    url: jdbc:mysql://120.25.216.140:3306/comic
#    driver-class-name: com.mysql.jdbc.Driver
#mybatis:
#  config-location: classpath:mybatis/mybatisConfig.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml
server:
  port: 8888

