server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 120.25.216.140:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  datasource:
    username: user2
    password: 2590868
    url: jdbc:mysql://120.25.216.140:3306/comic
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  config-location: classpath:mybatis/mybatisConfig.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: '*'
