server:
  port: 8081

spring:
  application:
    name: cloud-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 120.25.216.140:8848


# 开启压缩 节省资源 提升性能
feign:
  compression:
    request:
      # 开启数据压缩请求
      enabled: true
      # 压缩数据类型
      mime-types: text/xml, application/xml, application/json
      # 数据压缩下限 2048表示传输数据大于2048 才会进行数据压缩(最小压缩值标准)
      min-request-size: 2048
    # 开启数据压缩响应
    response:
      enabled: true




